version: "3"

services:
  http:
    build: poggadaj-http
    restart: always
    ports:
      - "80:8080"

  tcp:
    build: poggadaj-tcp
    restart: always
    ports:
      - "8074:8074"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: postgres:17
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=poggadaj
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:8.12
    restart: always
    ports:
      - "8822:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_DISABLE_POSTFIX=true
