version: "3"

services:
  http:
    build: poggadaj-http
    restart: always
    ports:
      - "80:8080"
    environment:
      - LISTEN_ADDRESS=0.0.0.0
      - LISTEN_PORT=8080
      - DB_ADDRESS=db
      - DB_PASSWORD=${DB_PASSWORD}
      - GG_SERVICE_IP=${GG_SERVICE_IP}
      - GG_SERVICE_PORT=${GG_SERVICE_PORT}

  nginx:
    build: poggadaj-nginx
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build: poggadaj-web
    restart: always
    environment:
      - NODE_ENV=production

  api:
    build: poggadaj-api
    restart: always
    environment:
      - LISTEN_ADDRESS=0.0.0.0
      - LISTEN_PORT=8080
      - DB_ADDRESS=db
      - DB_PASSWORD=${DB_PASSWORD}
      - CACHE_ADDRESS=cache
      - GG_SEED=${GG_SEED}

  tcp:
    build: poggadaj-tcp
    restart: always
    ports:
      - "8074:8074"
    environment:
      - LISTEN_ADDRESS=0.0.0.0
      - DB_ADDRESS=db
      - DB_PASSWORD=${DB_PASSWORD}
      - CACHE_ADDRESS=cache
      - GG_SEED=${GG_SEED}

  db:
    image: postgres:17
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=poggadaj
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  cache:
    image: valkey/valkey:8.0-alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
